{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9a966147-6bbc-4c7d-90bc-77e6585c63a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "#create a function and lsit out the items in the list \n",
    "class SubfieldsInAI():\n",
    "def subfields() :\n",
    "    subFieldsinAI=[\"Machine Learning\",\"Neural Networks\",\"Vision\",\"Robotics\",\"Speech Processing\",\"Natural Language Processing\"]\n",
    "    print(\"Sub fields in AI are :\")\n",
    "    fields=\" \"\n",
    "    for fields in subFieldsinAI:\n",
    "        print(fields)\n",
    "\n",
    "#Create a function that checks whether the given number is odd or even\n",
    "class OddEven():  \n",
    "def oddEven():\n",
    "    num=int(input(\"Enter a number : \")) \n",
    "    if (num%2 == 0) : \n",
    "       print(num, \"is even number\")\n",
    "    else : \n",
    "       print(num, \"is odd number\") \n",
    "\n",
    "#Create a function that tells eligibility of marriage for male and female according to their age limit \n",
    "#like 21 for male and 18 for female\n",
    "class EligibilityForMarriage():\n",
    "def eligible():\n",
    "    gender = input(\"Enter your gender :\")\n",
    "    age = int(input(\"Enter your age :\"))\n",
    "    if (gender == \"male\") :\n",
    "       if (age >= 21) : \n",
    "           print(\"Eligible\")\n",
    "       else : \n",
    "           print(\"Not Eligible\")\n",
    "    elif (gender == \"female\") :\n",
    "       if (age >= 18) : \n",
    "           print(\"Eligible\")\n",
    "       else : \n",
    "           print(\"Not Eligible\")\n",
    "           \n",
    "#Calculate the percentage of your 10th mark\n",
    "class FindPercent():\n",
    "def percentage():\n",
    "    subjects = [\"English\",\"Tamil\",\"Mathematics\",\"Science\",\"Social Science\"]\n",
    "    total = 0 \n",
    "    for sub in subjects :\n",
    "        print(\"Enter your marks in \",sub, \":\")\n",
    "        marks = int(input())\n",
    "        total = total + marks\n",
    "    print(\"Percentage in tenth : \", total/5)\n",
    "\n",
    "#print area and perimeter of triangle using functions\n",
    "class triangle():\n",
    "def triangle() :\n",
    "    h1 = int(input(\"Enter height of the triangle  1:\"))\n",
    "    b1 = int(input(\"Enter breadth of the triangle 1:\"))\n",
    "    area = (h1 * b1 )/2\n",
    "    h3 = int(input(\"Enter height of the triangle 2 :\"))\n",
    "    h4 = int(input(\"Enter height of the triangle 2 :\"))\n",
    "    b2 = int(input(\"Enter breadth of the triangle 2 :\"))\n",
    "    perimeter = h3 + h4 + b2 \n",
    "    print(\"The area of first triangle is : \",area)\n",
    "    print(\"The perimeter of second triangle is : \", perimeter)    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
